config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'questions#index'

  resources :users do
    resources :questions do
      resources :responses, :except => [:index, :new]
    end
  end
  
  resources :questions do
    resources :responses, :except => [:index, :new]
  end

  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

 end

app/models/question.rb
class Question < ActiveRecord::Base

  has_many :responses
  belongs_to :user
  belongs_to :best_response, class_name: 'Response'
  validates :title, :presence => true
  validates :content, :presence => true

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @response = Response.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    @question.update(user_id: current_user.id)
    if @question.save
      flash[:notice] = "Thank you. Your very intelligent question has been posted."
      redirect_to '/'
    else
      flash[:alert] = "You have failed to complete your question form. Try again."
      redirect_to :back
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Your question has been updated."
      redirect_to question_path(@question)
    else
      flash[:alert] = "You've completely failed. Try again."
      redirect_to :back
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = "Your question is lost to the abyss."
    redirect_to '/'
  end

private
  def question_params
    params.require(:question).permit(:title, :content, :best_response_id, :user_id)
  end

end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :class => 'form-control' %>
  <%= f.label :content %>
  <%= f.text_area :content, :class => 'form-control' %>
  <%= f.submit class: 'btn btn-info'  %>

<% end %>

app/views/questions/edit.html.erb
<h2>Edit your question</h2>
<%= render "form" %>

<%= link_to "Delete question", question_path(@question),
                                 :data =>
                                {:confirm => "Are you sure?",
                                 :method => "delete"}, class: 'btn btn-danger' %>

app/views/questions/index.html.erb
<h2>All Questions</h2>
<ul>
  <% @questions.each do |question| %>
    <li>
      <%= link_to question.title, question_path(question) %>
    </li>
  <% end %>
</ul>

<% if current_user %>
  <%= link_to "Ask a question", new_question_path %>
<% end %>

app/views/questions/new.html.erb
<%= render "form" %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<% if @question.user == current_user %>
  <%= link_to "Edit Question", edit_question_path(@question) %>
<% end %>
<p>
  <%= @question.content %>
  ~ <%= link_to @question.user.email, user_path(@question.user) %>
</p>

<hr>
<h4>Comments:</h4>


<ul>
 <% if @question.best_response %>
  <li>Winnnner! <%= @question.best_response.content %> ~ <%= link_to @question.best_response.user.email, user_path(@question.best_response.user) %></li>
 <% end %>
<% @question.responses.each do |response| %>
  <% unless response == @question.best_response %>
    <li>
      <%= response.content %> ~ <%= link_to response.user.email, user_path(response.user) %>
      <% if response.user == current_user %>
        <%= link_to "Delete Response", question_response_path(@question, response),
                                        :data => {
                                                  :confirm => "You sure??",
                                                  :method => "delete" } %>
      <% end %>
      <% if @question.user == current_user %>
        <%= form_for @question do |f| %>
        <%= f.hidden_field :best_response_id, :value => response.id %>
        <%= f.submit "best response", class: 'btn btn-info btn-xs' %>
        <% end %>
      <% end %>
    </li>
    <% end %>
<% end %>
</ul>
<% if current_user %>
  <h4>Add a comment:</h4>
  <%= render 'responses/form' %>
<% end %>