config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'questions#index'

  resources :users do
    resources :questions do
      resources :responses, :except => [:index, :new]
    end
  end
  
  resources :questions do
    resources :responses, :except => [:index, :new]
  end

  get "/log-in" => "sessions#new", as: :log_in
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScienceOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><%= link_to "SCIENCE! | Overflow!", questions_path %></h1>

        <% if current_user %>
           <!-- link_to current_user.username, user_path(current_user.id) %> -->
           Hi <%= current_user.email %>!
           <%= link_to "My Profile", user_path(current_user) %>
          <%= link_to "log out", log_out_path %>
        <% else %>
          <%= link_to "new user", new_user_registration_path %>
          <%= link_to "log in", log_in_path %>
        <% end %>

        <h3></h3>
        <div class="col-md-3">
          <% if flash[:alert] %>
            <div class="alert">
              <%= flash[:alert] %>
            </div>
          <% end %>
          <div class="newton">
          </div>
        </div>
        <div class="col-md-6">
          <%= yield %>
        </div>
        <div class="col-md-3">
          <% if flash[:notice] %>
            <div class="notice">
              <%= flash[:notice] %>
            </div>
            <% end %>
          <div class="lovelace">
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>